name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # clone the code
      - name: Checkout
        uses: actions/checkout@v2

      # setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # setup docker compose 
      - run: pip3 install docker-compose --upgrade

      # setup google cloud cli
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - run: 'gcloud auth configure-docker europe-west4-docker.pkg.dev -q'

      # build & deploy
      - run: bash deploy.sh